version: '3'
services:
  db:
    image: mysql:5.7
    container_name: proyecto1_db
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: proyecto
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: proyecto1_web
    depends_on:
      - db
    volumes:
      - ./code/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true